// ─── Manifest Types (generated by Claude, imported by user) ─────────────────

export interface FactoryManifest {
  manifest_version: string
  project: ManifestProject
  shots: ManifestShot[]
}

export interface ManifestProject {
  name: string
  description: string
  created_at: string
  author?: string
}

export interface ManifestShot {
  id: string
  scene: string
  scene_slug: string
  description: string
  act: number
  order: number
  enabled: boolean
  frames: {
    first: FrameConfig | null
    middle: FrameConfig | null
    last: FrameConfig | null
  }
  video: VideoConfig
  video_alt: VideoConfig | null
  extend: ExtendConfig | null
  pipeline_overrides: PipelineOverrides | null
  audio_layers: AudioLayers | null
  metadata: ShotMetadata
}

// ─── Frame Configuration ────────────────────────────────────────────────────

export type FrameSource = 'generate' | 'file' | 'previous_shot' | 'url'

export interface FrameConfigGenerate {
  source: 'generate'
  prompt: string
  negative_prompt?: string
  width: number
  height: number
  steps: number
  guidance: number
  seed: number | null
  engine: string
}

export interface FrameConfigFile {
  source: 'file'
  path: string
}

export interface FrameConfigPreviousShot {
  source: 'previous_shot'
  shot_id: string
  frame_position: 'first' | 'last'
}

export interface FrameConfigUrl {
  source: 'url'
  url: string
}

export type FrameConfig =
  | FrameConfigGenerate
  | FrameConfigFile
  | FrameConfigPreviousShot
  | FrameConfigUrl

// ─── Video Configuration ────────────────────────────────────────────────────

export interface VideoConfig {
  prompt: string
  model: string
  duration: string
  resolution: string
  fps: number
  iterations: number
  aspect_ratio: string
  audio: boolean
  camera_motion: string
  prompt_enhance: boolean
  spatial_upscale: boolean
  temporal_upscale: boolean
  film_grain: boolean
}

// ─── Extend Configuration ───────────────────────────────────────────────────

export interface ExtendPass {
  add_seconds: number
  prompt: string
}

export interface ExtendConfig {
  enabled: boolean
  target_duration_seconds: number
  method: 'extend_end' | 'extend_start'
  extend_prompt?: string
  match_original_prompt?: boolean
  iterations?: number
  resolution?: string
  fps?: number
  audio?: boolean
  film_grain?: boolean
  passes?: ExtendPass[]
}

// ─── Pipeline Configuration ─────────────────────────────────────────────────

export interface SamplerOverride {
  name: string
  cfg_scale: number
  steps?: number
}

export interface LoraConfig {
  enabled: boolean
  preset?: string
  file?: string
  strength: number
}

export interface PipelineOverrides {
  sampler?: SamplerOverride
  loras?: {
    speed?: LoraConfig
    camera?: LoraConfig
    style?: LoraConfig
    ic_lora?: LoraConfig
  }
}

// ─── Audio Layers ───────────────────────────────────────────────────────────

export interface AudioLayerConfig {
  source: 'file'
  path: string
  volume: number
  start_offset_ms?: number
  fade_in_ms?: number
  fade_out_ms?: number
  loop?: boolean
}

export interface AudioLayers {
  narration: AudioLayerConfig | null
  music: AudioLayerConfig | null
  sfx: AudioLayerConfig | null
}

// ─── Shot Metadata ──────────────────────────────────────────────────────────

export interface ShotMetadata {
  narration?: string
  duration_seconds?: number
  source_books?: string[]
  color_grade_note?: string
  edit_note?: string
  timecode_estimate?: string
}

// ─── Runtime State Types ────────────────────────────────────────────────────

export type ShotStatus =
  | 'idle'
  | 'generating-frame'
  | 'frame-ready'
  | 'rendering-video'
  | 'video-ready'
  | 'approved'
  | 'error'
  | 'disabled'

export interface ShotIteration {
  id: string
  path: string
  url: string
  seed?: number
  createdAt: number
}

export interface FactoryShot {
  manifest: ManifestShot
  status: ShotStatus
  error?: string
  frameIterations: ShotIteration[]
  activeFrameIndex: number
  videoIterations: ShotIteration[]
  activeVideoIndex: number
  queueItemId?: string
}

export type FactoryPhase =
  | 'idle'
  | 'generating-frames'
  | 'reviewing'
  | 'rendering'
  | 'organizing'
  | 'complete'

export interface FactoryProgress {
  completed: number
  total: number
  currentShotId: string | null
  startTime: number | null
}

// ─── GPU & Pipeline Types ───────────────────────────────────────────────────

export interface GpuCapabilities {
  available: boolean
  name: string
  vramGb: number
  cudaAvailable: boolean
}

export type CheckpointVariant =
  | 'dev'
  | 'dev-fp8'
  | 'distilled'
  | 'distilled-fp8'
  | 'gguf-q8'
  | 'gguf-q4'

export interface PipelinePreset {
  id: string
  label: string
  checkpoint: CheckpointVariant
  steps: number
  cfg: number
  speedLora: boolean
  sampler: string
  minVram: number
  description: string
}

export interface VramEstimate {
  checkpoint: number  // GB on disk
  generation: number  // GB needed during generation
}

export interface ValidationWarning {
  shotId: string
  severity: 'error' | 'warning'
  message: string
}

// ─── Creative Console Types ─────────────────────────────────────────────────

export interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: number
  shotPreviews?: ShotPreview[]
}

export interface ShotPreview {
  shot: ManifestShot
  action: 'add' | 'update' | 'delete'
  applied: boolean
}

// ─── Factory Settings Types ─────────────────────────────────────────────────

export type AiProvider = 'anthropic' | 'local' | 'claude-max' | 'hybrid'

export interface FactorySettings {
  // AI provider
  aiProvider: AiProvider
  anthropicApiKey: string
  anthropicModel: string
  proxyUrl: string
  proxyToken: string
  proxyModel: string
  // Generation defaults
  defaultDuration: number
  defaultResolution: string
  defaultFps: number
  defaultIterations: number
  defaultAspectRatio: string
  // Advanced timing
  delayBetweenShots: number
  renderTimeout: number
  maxRetries: number
  progressPollInterval: number
  autoSaveInterval: number
  crashRecovery: boolean
}
